repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.4.0
    hooks:
      - id: check-added-large-files
        args: ["--maxkb=500"]
      - id: check-case-conflict
      - id: check-json
        exclude: "^.vscode/tasks.json|^.devcontainer/devcontainer.json"
      - id: check-merge-conflict
      - id: check-xml
      - id: detect-aws-credentials
        args: ["--allow-missing-credentials"]
      - id: detect-private-key
      - id: end-of-file-fixer
        exclude: "^.idea/.*$"
      - id: forbid-new-submodules
      - id: mixed-line-ending
      # - id: no-commit-to-branch
      #   args: [--branch, main]
      - id: trailing-whitespace
        args: [--markdown-linebreak-ext=md]
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v2.7.1
    hooks:
      - id: prettier
  - repo: https://github.com/ambv/black
    rev: 23.3.0
    hooks:
      - id: black
        language_version: python3.11
        additional_dependencies: ["click==8.0.4"]
  - repo: local
    hooks:
      - id: pylint
        name: pylint
        entry: bash -c 'PIPENV_VENV_IN_PROJECT=1 pipenv run pylint *.py'
        language: system
        types: [python]
        require_serial: true
